// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd4i1QGEDxMgC7HODSuG-3JJd8k-FRpio',
    appId: '1:936345294181:web:8f8e5f85b0196f436a3d8c',
    messagingSenderId: '936345294181',
    projectId: 'medminder-b6203',
    authDomain: 'medminder-b6203.firebaseapp.com',
    storageBucket: 'medminder-b6203.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhchI9SimR6kEGjBqX2qA1wKX68vc6Bn4',
    appId: '1:936345294181:android:af3981db90089ac56a3d8c',
    messagingSenderId: '936345294181',
    projectId: 'medminder-b6203',
    storageBucket: 'medminder-b6203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfWhZmpFgoX06a2G6L_j0lvMUHIt_JT5k',
    appId: '1:936345294181:ios:4d14795e685f2c9a6a3d8c',
    messagingSenderId: '936345294181',
    projectId: 'medminder-b6203',
    storageBucket: 'medminder-b6203.firebasestorage.app',
    iosBundleId: 'com.example.medminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfWhZmpFgoX06a2G6L_j0lvMUHIt_JT5k',
    appId: '1:936345294181:ios:4d14795e685f2c9a6a3d8c',
    messagingSenderId: '936345294181',
    projectId: 'medminder-b6203',
    storageBucket: 'medminder-b6203.firebasestorage.app',
    iosBundleId: 'com.example.medminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd4i1QGEDxMgC7HODSuG-3JJd8k-FRpio',
    appId: '1:936345294181:web:a60a8e4561c8ca576a3d8c',
    messagingSenderId: '936345294181',
    projectId: 'medminder-b6203',
    authDomain: 'medminder-b6203.firebaseapp.com',
    storageBucket: 'medminder-b6203.firebasestorage.app',
  );
}
